apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idsm-react-debug-ingress-http-6
  namespace: idsm-elixir-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "idsm-react-debugger-6.dyn.cloud.e-infra.cz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: idsm-react-debug
                port:
                  number: 80
